version: '3'
services:
  postgres:
    container_name: postgres
    image: 'postgres:15'
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - './pgsql:/var/lib/postgresql/data'
    networks:
      - todo
  
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "8080:80"
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - todo

networks:
  todo:
    driver: bridge

volumes:
  pgsql:
    driver: local
